import {
  User,
  Idea,
  InvestorProfile,
  IdeaApplication,
  Connection,
  Conversation,
  Message,
  Opportunity,
  Meeting,
  Notification,
  Report,
  AuditLog,
  SubscriptionPlan,
} from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-founder-1',
    name: 'Rahul Sharma',
    email: 'founder@ideasoch.com',
    role: 'IDEA_MAKER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    title: 'Founder & Engineer, CleanGrid AI',
    location: 'Bengaluru, India',
    verified: true,
    bio: 'Former energy systems architect at Schneider Electric. Building decentralized algorithmic microgrid energy balancing for smart industrial parks.',
    experienceYears: 8,
    skills: ['Energy Systems', 'Embedded IoT', 'Python', 'B2B Sales', 'Microgrid Architecture'],
    linkedIn: 'https://linkedin.com/in/rahul-sharma-energy',
    website: 'https://cleangrid.tech',
    createdAt: '2026-01-15',
  },
  {
    id: 'user-founder-2',
    name: 'Dr. Ananya Sen',
    email: 'ananya@nivaandiagnostics.com',
    role: 'IDEA_MAKER',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    title: 'Co-Founder & Chief Scientist, Nivaan',
    location: 'Hyderabad, India',
    verified: true,
    bio: 'PhD in Biomedical Engineering from IISc. Developing rapid non-invasive multi-biomarker spectrometry screening for tier-2 clinic diagnostics.',
    experienceYears: 11,
    skills: ['Biomedical Optics', 'Spectrometry', 'Medical Device Regulation', 'Clinical Trials'],
    linkedIn: 'https://linkedin.com/in/dr-ananya-sen',
    website: 'https://nivaandiagnostics.com',
    createdAt: '2026-02-10',
  },
  {
    id: 'user-investor-1',
    name: 'Rajiv Mehta',
    email: 'investor@ideasoch.com',
    role: 'INVESTOR',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    title: 'Angel Investor & Managing Partner, Mehta Ventures',
    location: 'Mumbai, India',
    verified: true,
    bio: 'Ex-founder of PayMatrix (acquired). Investing in early-stage Indian B2B SaaS, CleanTech, and FinTech infrastructure. Portfolio across 24 startups.',
    experienceYears: 16,
    skills: ['Seed Investments', 'FinTech', 'SaaS Scaling', 'Go-To-Market', 'Board Governance'],
    linkedIn: 'https://linkedin.com/in/rajiv-mehta-investor',
    website: 'https://mehtaventures.in',
    createdAt: '2025-11-20',
  },
  {
    id: 'user-investor-2',
    name: 'Dr. Priya Nair',
    email: 'priya@aarohanpartners.com',
    role: 'INVESTOR',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    title: 'Partner, Aarohan Seed Fund',
    location: 'Bengaluru, India',
    verified: true,
    bio: 'Physician-turned-venture investor backing pioneering HealthTech, MedTech devices, and AgriTech deeptech. 14 portfolio investments across South Asia.',
    experienceYears: 13,
    skills: ['HealthTech', 'AgriTech', 'IP Strategy', 'Clinical Validation', 'Seed Syndicates'],
    linkedIn: 'https://linkedin.com/in/dr-priya-nair',
    website: 'https://aarohanpartners.com',
    createdAt: '2025-12-05',
  },
  {
    id: 'user-admin-1',
    name: 'Ideasoch Moderation Lead',
    email: 'admin@ideasoch.com',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=160&auto=format&fit=crop&q=80',
    title: 'Platform Integrity & Compliance Officer',
    location: 'New Delhi, India',
    verified: true,
    bio: 'Responsible for investor verification, idea document security review, and platform curation standards.',
    experienceYears: 10,
    createdAt: '2025-01-01',
  },
];

export const INITIAL_IDEAS: Idea[] = [
  {
    id: 'idea-1',
    title: 'CleanGrid AI',
    headline: 'AI-Powered Microgrid Energy Arbitrage for Heavy Industry',
    quote: 'We slash peak electricity costs by 26% through autonomous real-time battery and solar routing without costly grid modifications.',
    tagline: 'Autonomous microgrid energy arbitrage and load balancing for manufacturing parks.',
    category: 'CleanTech & Energy',
    stage: 'MVP',
    fundingRequired: '₹45,00,000',
    fundingCurrency: 'INR',
    location: 'Bengaluru, Karnataka',
    summary: 'CleanGrid integrates on-premise solar, battery storage, and grid power using machine learning algorithms to reduce commercial electricity costs by 26% while avoiding peak tariff surges.',
    problem: 'Commercial manufacturing hubs in India face erratic peak-hour grid tariffs and demand charges, causing up to 30% waste in battery cycle efficiency due to manual switching.',
    solution: 'Hardware-agnostic edge controller paired with predictive neural networks that forecast solar generation 24h ahead and execute real-time power routing across microgrids.',
    targetMarket: 'Over 85,000 industrial clusters, tech parks, and cold-chain facilities across Maharashtra, Gujarat, and Karnataka.',
    tamSamSom: 'TAM: ₹14,200 Cr · SAM: ₹2,400 Cr · SOM: ₹180 Cr over 3 years.',
    businessModel: 'B2B SaaS subscription (₹18,000/month per facility) + 12% share of realized monthly grid electricity savings.',
    currentTraction: '3 paid pilot installations operational across Peenya Industrial Estate with 23.8% measured cost reduction; ₹4.2L ARR in signed pilot contracts.',
    unitEconomics: 'CAC: ₹45,000 · LTV: ₹4,80,000 · LTV/CAC: 10.6x · Payback Period: 3.5 months.',
    useOfFunds: '50% R&D and hardware certifications, 30% enterprise business development, 20% working capital.',
    founderId: 'user-founder-1',
    founderName: 'Rahul Sharma',
    founderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    founderBio: 'Former energy systems architect at Schneider Electric (8 yrs). MS in Power Systems.',
    founderLinkedIn: 'https://linkedin.com/in/rahul-sharma-energy',
    documents: [
      {
        title: 'Executive Summary & One Pager',
        fileName: 'CleanGrid_Executive_Summary.pdf',
        fileSize: '1.4 MB',
        fileType: 'pdf',
        isConfidential: false,
        url: '#',
      },
      {
        title: 'Confidential Pitch Deck & Unit Economics',
        fileName: 'CleanGrid_Series_Seed_Deck.pdf',
        fileSize: '4.8 MB',
        fileType: 'pdf',
        isConfidential: true,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 142,
    savesCount: 28,
    applicationsCount: 6,
    featured: true,
    createdAt: '2026-02-01',
    updatedAt: '2026-02-18',
  },
  {
    id: 'idea-2',
    title: 'Nivaan Diagnostics',
    headline: 'Non-Invasive Transdermal Optical Spectrometry Diagnostics',
    quote: 'Instant 90-second metabolic and organ biomarker reads at tier-2 primary health centers without drawing a single drop of venous blood.',
    tagline: 'Point-of-care non-invasive multi-biomarker optical diagnostic analyzer.',
    category: 'Healthcare & Life Sciences',
    stage: 'Prototype',
    fundingRequired: '₹80,00,000',
    fundingCurrency: 'INR',
    location: 'Hyderabad, Telangana',
    summary: 'A handheld Raman-spectroscopy analyzer that identifies early metabolic indicators and liver enzymes in under 90 seconds without drawing venous blood.',
    problem: 'Tier-2 and rural health clinics wait 48 to 72 hours for outsourced pathology lab results, delaying critical intervention for hepatic and renal metabolic anomalies.',
    solution: 'Proprietary transdermal optical sensor using narrow-band infrared scattering coupled with cloud-verified biomarker reference profiles.',
    targetMarket: 'Tier-2/3 diagnostic clinics, primary healthcare centers (PHCs), and mobile health screening camps.',
    tamSamSom: 'TAM: ₹9,800 Cr · SAM: ₹1,600 Cr · SOM: ₹120 Cr.',
    businessModel: 'Razor-and-blade model: Analyzer hardware sold at cost (₹35,000) with proprietary consumable optical test cartridges (₹85/test at 65% gross margin).',
    currentTraction: 'Bench prototype tested on 220 volunteer samples at Osmania Medical College with 94.2% sensitivity correlation against standard ELISA.',
    unitEconomics: 'Hardware Gross Margin: 25% · Reagent Cartridge Gross Margin: 68% · Projected recurring revenue per clinic: ₹14,000/mo.',
    useOfFunds: '60% CDSCO regulatory clearance & multi-centric clinical trial, 25% hardware miniaturization, 15% team expansion.',
    founderId: 'user-founder-2',
    founderName: 'Dr. Ananya Sen',
    founderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    founderBio: 'PhD in Biomedical Engineering, IISc Bengaluru. 11 years research in biomedical optics & medical instrumentation.',
    founderLinkedIn: 'https://linkedin.com/in/dr-ananya-sen',
    documents: [
      {
        title: 'Clinical Trial Preliminary Report',
        fileName: 'Nivaan_Clinical_Validation_Report.pdf',
        fileSize: '3.2 MB',
        fileType: 'pdf',
        isConfidential: true,
        url: '#',
      },
      {
        title: 'Non-Confidential Technical Overview',
        fileName: 'Nivaan_Device_Overview.pdf',
        fileSize: '2.1 MB',
        fileType: 'pdf',
        isConfidential: false,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 188,
    savesCount: 39,
    applicationsCount: 8,
    featured: true,
    createdAt: '2026-02-08',
    updatedAt: '2026-02-22',
  },
  {
    id: 'idea-3',
    title: 'KisanSetu',
    headline: 'Decentralized Solar Cold-Storage Pods & Mandi Arbitrage',
    quote: 'Eliminating 28% post-harvest spoilage for smallholder horticulture farmers by bringing modular solar refrigeration directly to village gates.',
    tagline: 'Decentralized farm-gate cold storage aggregation and algorithmic mandi arbitrage.',
    category: 'AgriTech & Food',
    stage: 'Early Traction',
    fundingRequired: '₹1,20,00,000',
    fundingCurrency: 'INR',
    location: 'Pune, Maharashtra',
    summary: 'KisanSetu deploys solar-powered micro cold-storage pods in village panchayats, linking horticulture farmers directly to regional institutional buyers.',
    problem: 'Over 28% of Indian perishable fruits and vegetables spoil within 72 hours of harvest due to lack of accessible primary refrigeration near smallholder farms.',
    solution: 'Modular 5-tonne solar cold containers managed via IoT temperature logs, backed by forward sale agreements with modern retail and food processors.',
    targetMarket: 'Horticulture farmers and agricultural cooperatives across Maharashtra, MP, and Andhra Pradesh.',
    tamSamSom: 'TAM: ₹32,000 Cr · SAM: ₹4,500 Cr · SOM: ₹250 Cr.',
    businessModel: 'Storage fee (₹1.80/kg/month) + 4.5% commission on facilitated farm-gate bulk sale contracts.',
    currentTraction: '14 active micro-pods deployed across Nashik & Satara; 420 farmers onboarded; ₹38L gross transacted produce in Q4.',
    useOfFunds: '55% pod manufacturing and lease capital, 25% supply chain logistics, 20% engineering & IoT platform.',
    founderId: 'user-founder-1',
    founderName: 'Vikram Deshmukh',
    founderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    founderBio: '2nd generation agribusiness leader, B.Tech IIT Bombay, former supply chain manager at ITC Agri-Business.',
    documents: [
      {
        title: 'KisanSetu Seed Investor Brief',
        fileName: 'KisanSetu_Pitch_2026.pdf',
        fileSize: '3.6 MB',
        fileType: 'pdf',
        isConfidential: false,
        url: '#',
      },
      {
        title: 'Cold Storage Pod Engineering Deck',
        fileName: 'KisanSetu_Hardware_Specs.pdf',
        fileSize: '2.8 MB',
        fileType: 'pdf',
        isConfidential: true,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 210,
    savesCount: 44,
    applicationsCount: 11,
    featured: true,
    createdAt: '2026-01-20',
    updatedAt: '2026-02-15',
  },
  {
    id: 'idea-4',
    title: 'FinOrbit',
    headline: 'Zero-Code GST Invoice Factoring API for Indian MSMEs',
    quote: 'Unlocking 90-day frozen working capital within 60 minutes through automated GST e-way bill risk scoring and NBFC liquidity pools.',
    tagline: 'Embedded invoice reconciliation and instant factoring API for SME supply chains.',
    category: 'FinTech & Capital',
    stage: 'MVP',
    fundingRequired: '₹60,00,000',
    fundingCurrency: 'INR',
    location: 'Mumbai, Maharashtra',
    summary: 'FinOrbit plugs directly into Indian accounting systems (Tally, Zoho) to verify GST e-invoices and match vetted vendors with NBFC liquidity providers in real-time.',
    problem: 'MSMEs wait 60 to 90 days for corporate payments, locking up critical operational cash flow while traditional bank working capital approval takes weeks.',
    solution: 'Zero-code ERP integration verifying GST e-way bills with an automated risk scoring engine that enables instant discounting at 1.4% monthly interest.',
    targetMarket: 'Over 450,000 registered manufacturing and wholesale suppliers with annual turnover between ₹2 Cr and ₹40 Cr.',
    tamSamSom: 'TAM: ₹18,000 Cr annual factoring volume · SAM: ₹3,200 Cr.',
    businessModel: '0.85% origination fee on funded invoices paid by lending partners + ₹4,999/month ERP connector SaaS fee.',
    currentTraction: '₹3.4 Cr cumulative invoices processed in closed beta; 3 NBFC lending partners onboarded; zero default rate to date.',
    useOfFunds: '40% NBFC escrow risk underwriting & compliance, 35% enterprise sales team, 25% security & cloud architecture.',
    founderId: 'user-founder-2',
    founderName: 'Tanvi Gupta',
    founderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=160&auto=format&fit=crop&q=80',
    founderBio: 'Chartered Accountant & FinTech product leader with 7 years at Razorpay and ICICI Bank treasury.',
    documents: [
      {
        title: 'FinOrbit Pitch Deck & NBFC Partnership Terms',
        fileName: 'FinOrbit_Deck_Confidential.pdf',
        fileSize: '2.9 MB',
        fileType: 'pdf',
        isConfidential: true,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 165,
    savesCount: 31,
    applicationsCount: 7,
    featured: false,
    createdAt: '2026-02-12',
    updatedAt: '2026-02-24',
  },
  {
    id: 'idea-5',
    title: 'LogixFleet',
    headline: 'Algorithmic Return-Trip Freight Matching for Fleet Owners',
    quote: 'Eliminating empty return runs on long-haul transit corridors to double trucker margins and curb logistics emissions.',
    tagline: 'Intermodal freight return-trip aggregation for tier-2 truck fleets.',
    category: 'Logistics & Supply Chain',
    stage: 'Early Traction',
    fundingRequired: '₹90,00,000',
    fundingCurrency: 'INR',
    location: 'Ahmedabad, Gujarat',
    summary: 'Dynamic freight algorithmic marketplace that eliminates empty return runs for mid-sized long-haul transport operators across northern and western transit corridors.',
    problem: 'Over 38% of long-haul freight trucks in India return empty after delivery, cutting trucker margins by half and increasing logistics emissions.',
    solution: 'Geo-located WhatsApp-first dispatch bot matching verified return-haul shippers with passing fleet operators with digital transit insurance.',
    targetMarket: '1.2 million mid-sized fleet operators running 5 to 50 commercial vehicles in India.',
    tamSamSom: 'TAM: ₹24,000 Cr · SAM: ₹4,000 Cr.',
    businessModel: '5% transaction take-rate on booked return loads + value-added FASTag & fuel card credit margin.',
    currentTraction: '180 registered fleet owners; 650 monthly completed trips; ₹22L monthly GMV.',
    useOfFunds: '50% corridor hub expansion in Delhi-NCR and Mumbai corridors, 30% tech, 20% driver support.',
    founderId: 'user-founder-1',
    founderName: 'Rohan Kulkarni',
    founderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&auto=format&fit=crop&q=80',
    founderBio: 'Former operations manager at Delhivery. 9 years in surface transport operations.',
    documents: [
      {
        title: 'LogixFleet Investor Brief',
        fileName: 'LogixFleet_Overview.pdf',
        fileSize: '1.8 MB',
        fileType: 'pdf',
        isConfidential: false,
        url: '#',
      },
      {
        title: 'Corridor Density Financials',
        fileName: 'LogixFleet_Corridor_Model.pdf',
        fileSize: '2.2 MB',
        fileType: 'pdf',
        isConfidential: true,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 130,
    savesCount: 22,
    applicationsCount: 5,
    featured: false,
    createdAt: '2026-01-28',
    updatedAt: '2026-02-19',
  },
  {
    id: 'idea-6',
    title: 'EdVeda Enterprise',
    headline: 'Vernacular Voice-Guided AI Simulations for Plant Technicians',
    quote: 'Solving 45% technician turnover with interactive multilingual shopfloor training in 4 regional languages right on mobile screens.',
    tagline: 'Vernacular AI training modules for manufacturing shopfloor technicians.',
    category: 'EdTech & Learning',
    stage: 'Prototype',
    fundingRequired: '₹35,00,000',
    fundingCurrency: 'INR',
    location: 'Chennai, Tamil Nadu',
    summary: 'Voice-interactive multi-lingual training simulations teaching precision machining and safety protocols to industrial technicians on mobile devices.',
    problem: 'Industrial plants face 45% annual technician turnover and heavy downtime from onboarding delays due to English-only manual training materials.',
    solution: 'Interactive micro-learning modules in Hindi, Tamil, Telugu, and Marathi with voice-evaluated SOP comprehension tests.',
    targetMarket: 'Auto-ancillary, heavy equipment, and electronics manufacturing plants.',
    tamSamSom: 'TAM: ₹6,500 Cr · SAM: ₹900 Cr.',
    businessModel: 'Annual enterprise license: ₹2,400 per active technician seat.',
    currentTraction: 'Pilots deployed with 2 tier-1 automotive suppliers in Chennai industrial belt; 92% course completion rate.',
    useOfFunds: '60% regional NLP voice engine training, 25% direct B2B corporate sales, 15% operations.',
    founderId: 'user-founder-2',
    founderName: 'Meera Iyer',
    founderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    founderBio: 'Former instructional design lead at Tata Motors. M.Ed and Cognitive Psychology specialist.',
    documents: [
      {
        title: 'EdVeda Executive Overview',
        fileName: 'EdVeda_Deck.pdf',
        fileSize: '2.5 MB',
        fileType: 'pdf',
        isConfidential: false,
        url: '#',
      },
    ],
    status: 'Approved',
    viewsCount: 98,
    savesCount: 17,
    applicationsCount: 4,
    featured: false,
    createdAt: '2026-02-14',
    updatedAt: '2026-02-20',
  },
];

export const INITIAL_INVESTORS: InvestorProfile[] = [
  {
    userId: 'user-investor-1',
    name: 'Rajiv Mehta',
    title: 'Managing Partner',
    organization: 'Mehta Ventures',
    location: 'Mumbai, Maharashtra',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    verified: true,
    verificationStatus: 'verified',
    bio: 'Experienced entrepreneur and angel investor backing exceptional founders building infrastructure for India and global markets. Former founder of PayMatrix (acquired).',
    investmentThesis: 'We back capital-efficient founders with deep domain experience tackling fundamental B2B workflow bottlenecks, energy transition infrastructure, and supply chain digitization.',
    minTicket: '₹15 Lakhs',
    maxTicket: '₹1.5 Crores',
    preferredIndustries: ['CleanTech & Energy', 'FinTech & Capital', 'B2B SaaS & AI', 'Logistics & Supply Chain'],
    preferredStages: ['Prototype', 'MVP', 'Early Traction'],
    preferredLocations: ['Bengaluru', 'Mumbai', 'Delhi-NCR', 'Pune', 'Hyderabad'],
    areasOfExpertise: ['Early-Stage Go-to-Market', 'FinTech Regulatory Frameworks', 'B2B Sales Hiring', 'Unit Economics'],
    portfolio: [
      { name: 'OmniVolt', stage: 'Series A', sector: 'CleanTech', year: '2024' },
      { name: 'QuickLedger', stage: 'Pre-Series A', sector: 'FinTech', year: '2025' },
      { name: 'KargoSync', stage: 'Seed', sector: 'Logistics', year: '2025' },
    ],
    discoveryCreditsRemaining: 2,
    totalCreditsGranted: 3,
    planId: 'pro',
    subscriptionPlan: 'monthly',
    subscriptionBillingCycle: 'monthly',
    chatCreditsTotal: 5,
    chatCreditsUsed: 2,
    activeChatIds: ['idea-1', 'idea-3'],
    linkedIn: 'https://linkedin.com/in/rajiv-mehta-investor',
    website: 'https://mehtaventures.in',
  },
  {
    userId: 'user-investor-2',
    name: 'Dr. Priya Nair',
    title: 'Partner & Life Sciences Lead',
    organization: 'Aarohan Seed Fund',
    location: 'Bengaluru, Karnataka',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    verified: true,
    verificationStatus: 'verified',
    bio: 'Physician and health-tech investor. Focuses on clinically validated hardware, diagnostic medical devices, and bio-agriculture innovations across India.',
    investmentThesis: 'Investing in scientific rigor and defensible intellectual property that dramatically reduces health and agricultural delivery costs for emerging markets.',
    minTicket: '₹25 Lakhs',
    maxTicket: '₹2 Crores',
    preferredIndustries: ['Healthcare & Life Sciences', 'AgriTech & Food', 'B2B SaaS & AI'],
    preferredStages: ['Research & Validation', 'Prototype', 'MVP'],
    preferredLocations: ['Bengaluru', 'Hyderabad', 'Chennai', 'Pune'],
    areasOfExpertise: ['Clinical Trial Design', 'Medical Device Approvals', 'IP Moats', 'Hospital Distribution'],
    portfolio: [
      { name: 'AuraCardio', stage: 'Pre-Series A', sector: 'HealthTech', year: '2024' },
      { name: 'BrioBio', stage: 'Seed', sector: 'BioTech', year: '2025' },
      { name: 'CropShield AI', stage: 'Seed', sector: 'AgriTech', year: '2025' },
    ],
    discoveryCreditsRemaining: 3,
    totalCreditsGranted: 3,
    planId: 'pro',
    subscriptionPlan: 'yearly',
    subscriptionBillingCycle: 'yearly',
    chatCreditsTotal: 5,
    chatCreditsUsed: 1,
    activeChatIds: ['idea-2'],
    linkedIn: 'https://linkedin.com/in/dr-priya-nair',
    website: 'https://aarohanpartners.com',
  },
  {
    userId: 'user-investor-3',
    name: 'Amit Patel',
    title: 'Syndicate Lead & Angel',
    organization: 'Apex Founders Network',
    location: 'Ahmedabad & Mumbai',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&auto=format&fit=crop&q=80',
    verified: true,
    verificationStatus: 'verified',
    bio: 'Active angel backing 30+ technology startups. Passionate about manufacturing automation, logistics tech, and export enablement.',
    investmentThesis: 'Look for unsexy, high-margin, sticky enterprise solutions solving hard industrial problems with clear payback periods for buyers.',
    minTicket: '₹10 Lakhs',
    maxTicket: '₹75 Lakhs',
    preferredIndustries: ['Logistics & Supply Chain', 'B2B SaaS & AI', 'Consumer & D2C'],
    preferredStages: ['MVP', 'Early Traction', 'Scaling'],
    preferredLocations: ['Gujarat', 'Maharashtra', 'Delhi-NCR'],
    areasOfExpertise: ['Supply Chain Distribution', 'Export Channels', 'Working Capital Debt', 'Angel Syndicates'],
    portfolio: [
      { name: 'ShipEasy', stage: 'Series A', sector: 'Logistics', year: '2023' },
      { name: 'BharatSteelTech', stage: 'Seed', sector: 'B2B', year: '2024' },
    ],
    discoveryCreditsRemaining: 15,
    totalCreditsGranted: 25,
    planId: 'pro',
    subscriptionPlan: 'monthly',
    subscriptionBillingCycle: 'monthly',
    chatCreditsTotal: 5,
    chatCreditsUsed: 4,
    activeChatIds: ['idea-4', 'idea-5'],
    linkedIn: 'https://linkedin.com/in/amit-patel-angel',
  },
  {
    userId: 'user-investor-4',
    name: 'Anand Verma',
    title: 'Principal',
    organization: 'Kaveri Capital',
    location: 'New Delhi, India',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    verified: true,
    verificationStatus: 'verified',
    bio: 'Deep tech and industrial transformation investor. Focuses on founders commercializing patents and proprietary engineering breakthroughs.',
    investmentThesis: 'Backing world-class engineering teams building defensive IP across renewable energy, robotics, and advanced semiconductor packaging.',
    minTicket: '₹50 Lakhs',
    maxTicket: '₹3.5 Crores',
    preferredIndustries: ['CleanTech & Energy', 'Healthcare & Life Sciences', 'B2B SaaS & AI'],
    preferredStages: ['Prototype', 'MVP', 'Early Traction'],
    preferredLocations: ['Pan India'],
    areasOfExpertise: ['Institutional Co-investing', 'Hardware Manufacturing Scale', 'Patent Portfolios'],
    portfolio: [
      { name: 'IonDynamics', stage: 'Series A', sector: 'CleanTech', year: '2024' },
      { name: 'VayuSensor', stage: 'Pre-Series A', sector: 'Hardware', year: '2025' },
    ],
    discoveryCreditsRemaining: 30,
    totalCreditsGranted: 50,
    planId: 'fund',
    subscriptionPlan: 'yearly',
    subscriptionBillingCycle: 'yearly',
    chatCreditsTotal: 5,
    chatCreditsUsed: 0,
    activeChatIds: [],
    linkedIn: 'https://linkedin.com/in/anand-verma-kaveri',
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Technical Co-founder & Chief Technology Officer',
    type: 'Co-founder',
    postedById: 'user-founder-1',
    postedByName: 'CleanGrid AI / Rahul Sharma',
    postedByRole: 'Founder, CleanGrid AI',
    postedByAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    verified: true,
    location: 'Bengaluru, Karnataka',
    isRemote: false,
    summary: 'Seeking an experienced systems engineer to architect our distributed industrial edge-controller firmware and real-time power dispatch microservices.',
    description: 'CleanGrid is expanding from 3 pilot facilities to 25 commercial installations. We need a hands-on technical co-founder to lead our embedded systems and cloud telemetry infrastructure.',
    requirements: [
      '5+ years in embedded C/C++, Rust, or Python for IoT systems',
      'Familiarity with industrial protocols (Modbus, CAN bus, MQTT)',
      'Experience in high-reliability cloud telemetry architectures (AWS/GCP)',
      'Passion for climate tech and renewable microgrid systems',
    ],
    skills: ['Embedded C/C++', 'Rust', 'MQTT', 'Distributed Systems', 'IoT Security'],
    compensationOrEquity: '12% – 18% Equity + ₹1.5L/mo stipend post-seed',
    deadline: '2026-11-30',
    applicationMethod: 'INTERNAL',
    status: 'Published',
    viewsCount: 340,
    applicationsCount: 14,
    createdAt: '2026-02-10',
  },
  {
    id: 'opp-2',
    title: 'Strategic Cold Chain & Warehousing Partner',
    type: 'Partnership',
    postedById: 'user-founder-1',
    postedByName: 'KisanSetu Agricultural Network',
    postedByRole: 'Agricultural Cooperative Backer',
    postedByAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    verified: true,
    location: 'Maharashtra & Gujarat',
    isRemote: false,
    summary: 'Inviting regional warehousing and cold-chain operators to integrate their secondary storage facilities into the KisanSetu digital dispatch network.',
    description: 'We are seeking forward-looking cold storage owners with facilities along NH-48 and NH-52 to earn guaranteed revenue by hosting our IoT-monitored consolidation hubs.',
    requirements: [
      'Licensed temperature-controlled facility with 50+ tonnes capacity',
      'Uninterrupted three-phase power or solar backup',
      'Truck-loading ramp accessible for 16-tonne freight carriers',
      'Willingness to integrate temperature data loggers',
    ],
    skills: ['Cold Storage Ops', 'Logistics Management', 'HACCP Standards', 'APMC Mandi Knowledge'],
    compensationOrEquity: 'Long-term revenue share (₹2.20/kg booked throughput)',
    deadline: '2026-12-15',
    applicationMethod: 'INTERNAL',
    status: 'Published',
    viewsCount: 195,
    applicationsCount: 6,
    createdAt: '2026-02-14',
  },
  {
    id: 'opp-3',
    title: 'Lead Clinical Validation & Medical Device Regulatory Consultant',
    type: 'Consulting',
    postedById: 'user-founder-2',
    postedByName: 'Nivaan Diagnostics / Dr. Ananya Sen',
    postedByRole: 'Chief Scientist, Nivaan',
    postedByAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    verified: true,
    location: 'Hyderabad / Remote',
    isRemote: true,
    summary: 'Contract role to direct CDSCO Class B medical device approval dossier submission and multi-centric trial protocols.',
    description: 'We require an experienced medical regulatory consultant with deep experience guiding novel optical in-vitro diagnostic (IVD) hardware through Indian regulatory audits.',
    requirements: [
      'Successful track record with CDSCO Medical Device Rules 2017',
      'Experience authoring clinical investigation plans for diagnostics',
      'ISO 13485 audit readiness expertise',
    ],
    skills: ['CDSCO Regulatory', 'ISO 13485', 'IVD Clinical Protocols', 'Medical Device Dossiers'],
    compensationOrEquity: '₹1,50,000 – ₹2,50,000 / month retainer (6-month contract)',
    deadline: '2026-10-30',
    applicationMethod: 'INTERNAL',
    status: 'Published',
    viewsCount: 280,
    applicationsCount: 9,
    createdAt: '2026-02-18',
  },
  {
    id: 'opp-4',
    title: 'Seed Investment Syndicate: ₹60L Round in Supply Chain FinTech',
    type: 'Investment',
    postedById: 'user-investor-1',
    postedByName: 'Mehta Ventures Syndicate',
    postedByRole: 'Lead Angel Investor',
    postedByAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    verified: true,
    location: 'Mumbai, India',
    isRemote: true,
    summary: 'Opening allocation for accredited angel investors to co-invest alongside Mehta Ventures in a vetted SME supply chain invoice reconciliation API.',
    description: 'We are leading a ₹60L seed financing round in FinOrbit. We are allocating ₹25L to 4-5 accredited angel investors on Ideasoch who can add strategic distribution value.',
    requirements: [
      'Accredited Angel Investor status',
      'Minimum ticket size ₹5,00,000',
      'Ability to offer advisory in enterprise banking or vendor distribution',
    ],
    skills: ['Angel Investing', 'FinTech Due Diligence', 'SME Banking'],
    compensationOrEquity: 'Standard CCPS investment at ₹7.5 Cr pre-money valuation',
    deadline: '2026-11-15',
    applicationMethod: 'EXTERNAL',
    externalUrl: 'https://mehtaventures.in/syndicate/finorbit',
    status: 'Published',
    viewsCount: 420,
    applicationsCount: 18,
    createdAt: '2026-02-15',
  },
];

export const INITIAL_APPLICATIONS: IdeaApplication[] = [
  {
    id: 'app-1',
    ideaId: 'idea-1',
    ideaTitle: 'CleanGrid AI',
    ideaCategory: 'CleanTech & Energy',
    founderId: 'user-founder-1',
    founderName: 'Rahul Sharma',
    investorId: 'user-investor-1',
    investorName: 'Rajiv Mehta',
    investorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
    status: 'In Discussion',
    pitchNote: 'Hi Rajiv, following your investments in CleanTech infrastructure, CleanGrid has demonstrated 23.8% grid peak shaving across 3 manufacturing installations in Bengaluru. Would love to share our Series Seed metrics.',
    appliedAt: '2026-02-10',
    updatedAt: '2026-02-18',
  },
  {
    id: 'app-2',
    ideaId: 'idea-1',
    ideaTitle: 'CleanGrid AI',
    ideaCategory: 'CleanTech & Energy',
    founderId: 'user-founder-1',
    founderName: 'Rahul Sharma',
    investorId: 'user-investor-4',
    investorName: 'Anand Verma',
    investorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&auto=format&fit=crop&q=80',
    status: 'Shortlisted',
    pitchNote: 'Dear Anand, we noticed Kaveri Capital\'s thesis on industrial IoT and grid edge hardware. We have completed pilot test runs and have our edge patent filed.',
    appliedAt: '2026-02-12',
    updatedAt: '2026-02-20',
  },
  {
    id: 'app-3',
    ideaId: 'idea-2',
    ideaTitle: 'Nivaan Diagnostics',
    ideaCategory: 'Healthcare & Life Sciences',
    founderId: 'user-founder-2',
    founderName: 'Dr. Ananya Sen',
    investorId: 'user-investor-2',
    investorName: 'Dr. Priya Nair',
    investorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
    status: 'Meeting',
    pitchNote: 'Respected Dr. Priya, Nivaan has completed preliminary clinical testing on 220 samples with 94.2% correlation for non-invasive metabolic screening. We are raising our seed round for CDSCO trials.',
    appliedAt: '2026-02-09',
    updatedAt: '2026-02-19',
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    participantIds: ['user-founder-1', 'user-investor-1'],
    otherParticipant: {
      id: 'user-investor-1',
      name: 'Rajiv Mehta',
      role: 'INVESTOR',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
      title: 'Managing Partner, Mehta Ventures',
      verified: true,
      online: true,
    },
    lastMessage: 'Rahul, I reviewed your Peenya pilot data. The peak shaving savings look genuine. Let us schedule a 30-min sync this Thursday.',
    lastMessageTimestamp: '10:45 AM',
    unreadCount: 1,
  },
  {
    id: 'conv-2',
    participantIds: ['user-founder-2', 'user-investor-2'],
    otherParticipant: {
      id: 'user-investor-2',
      name: 'Dr. Priya Nair',
      role: 'INVESTOR',
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      title: 'Partner, Aarohan Seed Fund',
      verified: true,
      online: false,
    },
    lastMessage: 'Dr. Ananya, please share the spectroscopy optical tolerance metrics when available.',
    lastMessageTimestamp: 'Yesterday',
    unreadCount: 0,
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-founder-1',
      senderName: 'Rahul Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
      content: 'Hello Rajiv, thank you for accepting our connection on Ideasoch. Attached is our verified pitch deck and pilot readings from the Peenya industrial hub.',
      attachments: [
        {
          name: 'CleanGrid_Series_Seed_Deck.pdf',
          size: '4.8 MB',
          type: 'pdf',
          url: '#',
        },
      ],
      createdAt: '2026-02-18T09:30:00Z',
    },
    {
      id: 'msg-2',
      conversationId: 'conv-1',
      senderId: 'user-investor-1',
      senderName: 'Rajiv Mehta',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
      content: 'Rahul, I reviewed your Peenya pilot data. The peak shaving savings look genuine. What is your current lead time on the edge microcontroller units?',
      createdAt: '2026-02-18T10:15:00Z',
    },
    {
      id: 'msg-3',
      conversationId: 'conv-1',
      senderId: 'user-founder-1',
      senderName: 'Rahul Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
      content: 'Our current procurement and assembly lead time is 18 days per unit. We source STM32 microcontrollers domestically in Pune and assemble locally in Bengaluru.',
      createdAt: '2026-02-18T10:32:00Z',
    },
    {
      id: 'msg-4',
      conversationId: 'conv-1',
      senderId: 'user-investor-1',
      senderName: 'Rajiv Mehta',
      senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&auto=format&fit=crop&q=80',
      content: 'Rahul, I reviewed your Peenya pilot data. The peak shaving savings look genuine. Let us schedule a 30-min sync this Thursday.',
      createdAt: '2026-02-18T10:45:00Z',
    },
  ],
  'conv-2': [
    {
      id: 'msg-201',
      conversationId: 'conv-2',
      senderId: 'user-founder-2',
      senderName: 'Dr. Ananya Sen',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
      content: 'Dear Dr. Priya, thank you for shortlisting Nivaan. I have updated our dossier with the ELISA test cross-validation results from Osmania Medical College.',
      createdAt: '2026-02-17T14:20:00Z',
    },
    {
      id: 'msg-202',
      conversationId: 'conv-2',
      senderId: 'user-investor-2',
      senderName: 'Dr. Priya Nair',
      senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=160&auto=format&fit=crop&q=80',
      content: 'Dr. Ananya, please share the spectroscopy optical tolerance metrics when available.',
      createdAt: '2026-02-17T17:05:00Z',
    },
  ],
};

export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'meet-1',
    title: 'CleanGrid AI — Investment Discussion with Rajiv Mehta',
    organizerId: 'user-investor-1',
    organizerName: 'Rajiv Mehta',
    participantId: 'user-founder-1',
    participantName: 'Rahul Sharma',
    participantAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&auto=format&fit=crop&q=80',
    date: '2026-09-24',
    time: '15:30 IST',
    durationMinutes: 30,
    meetingLink: 'https://meet.ideasoch.com/cleangrid-mehta-sync',
    notes: 'Review Peenya manufacturing pilot unit economics, firmware BOM, and discuss ₹45L co-investment term sheet structure.',
    status: 'Accepted',
    createdAt: '2026-02-18',
  },
  {
    id: 'meet-2',
    title: 'Nivaan Diagnostics — Preliminary Clinical Review',
    organizerId: 'user-investor-2',
    organizerName: 'Dr. Priya Nair',
    participantId: 'user-founder-2',
    participantName: 'Dr. Ananya Sen',
    participantAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=160&auto=format&fit=crop&q=80',
    date: '2026-09-26',
    time: '11:00 IST',
    durationMinutes: 45,
    meetingLink: 'https://meet.ideasoch.com/nivaan-aarohan-review',
    notes: 'Evaluate CDSCO Class B regulatory roadmap and clinical multi-centric trials timeline.',
    status: 'Requested',
    createdAt: '2026-02-19',
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-founder-1',
    title: 'Investor Viewed Your Idea',
    message: 'Rajiv Mehta (Managing Partner, Mehta Ventures) accessed your full business profile for CleanGrid AI.',
    link: '/ideas/idea-1',
    type: 'VIEW',
    isRead: false,
    createdAt: '15 minutes ago',
  },
  {
    id: 'notif-2',
    userId: 'user-founder-1',
    title: 'Application Shortlisted',
    message: 'Your application to Kaveri Capital has been moved to Shortlisted status.',
    link: '/dashboard/founder',
    type: 'APPLICATION',
    isRead: false,
    createdAt: '2 hours ago',
  },
  {
    id: 'notif-3',
    userId: 'user-founder-1',
    title: 'Meeting Confirmed',
    message: 'Rajiv Mehta accepted your sync for Thursday, Sep 24 at 3:30 PM IST.',
    link: '/meetings',
    type: 'MEETING',
    isRead: true,
    createdAt: '1 day ago',
  },
  {
    id: 'notif-4',
    userId: 'user-investor-1',
    title: 'New Idea Application Received',
    message: 'CleanGrid AI applied for seed investment matching your CleanTech thesis.',
    link: '/dashboard/investor',
    type: 'APPLICATION',
    isRead: false,
    createdAt: '3 hours ago',
  },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-1',
    reporterId: 'user-founder-1',
    targetType: 'PROFILE',
    targetId: 'user-suspicious-9',
    targetTitle: 'Apex Global Micro-Fin VC',
    reason: 'Fake investment opportunity',
    details: 'User claims to represent a non-existent Singapore fund and asked for upfront document processing fees before sharing term sheet.',
    status: 'INVESTIGATING',
    createdAt: '2026-02-15',
  },
  {
    id: 'rep-2',
    reporterId: 'user-investor-2',
    targetType: 'IDEA',
    targetId: 'idea-demo-99',
    targetTitle: 'AI Drone Farm Sprayer',
    reason: 'Copyright issue',
    details: 'Copied verbatim engineering schematics from published research at Cornell University without attribution.',
    status: 'PENDING',
    createdAt: '2026-02-17',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    action: 'DISCOVERY_CREDIT_USED',
    userId: 'user-investor-1',
    userName: 'Rajiv Mehta',
    targetType: 'IDEA',
    targetId: 'idea-1',
    details: 'Consumed 1 of 3 monthly discovery credits to unlock CleanGrid AI confidential financials & pitch deck.',
    timestamp: '2026-02-18 10:42:15 IST',
  },
  {
    id: 'audit-2',
    action: 'APPLICATION_SUBMITTED',
    userId: 'user-founder-1',
    userName: 'Rahul Sharma',
    targetType: 'APPLICATION',
    targetId: 'app-1',
    details: 'Submitted seed investment pitch to Rajiv Mehta (Mehta Ventures).',
    timestamp: '2026-02-10 14:18:22 IST',
  },
  {
    id: 'audit-3',
    action: 'IDEA_APPROVED',
    userId: 'user-admin-1',
    userName: 'Ideasoch Moderation Lead',
    targetType: 'IDEA',
    targetId: 'idea-1',
    details: 'Verified founder credentials and approved CleanGrid AI for public marketplace listing.',
    timestamp: '2026-02-01 11:05:00 IST',
  },
  {
    id: 'audit-4',
    action: 'MEETING_CONFIRMED',
    userId: 'user-investor-1',
    userName: 'Rajiv Mehta',
    targetType: 'MEETING',
    targetId: 'meet-1',
    details: 'Accepted meeting invitation with Rahul Sharma for Sep 24, 2026.',
    timestamp: '2026-02-18 10:46:00 IST',
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'monthly',
    name: 'Investor Monthly Pass',
    badge: 'Verified Investor',
    priceMonthly: 4999,
    currency: '₹',
    discoveryCreditsPerMonth: 5,
    popular: false,
    description: 'Billed monthly. Complete security background check required prior to account activation.',
    features: [
      'Mandatory 24-hr security background check & verification',
      '5 Direct bilateral chats with founders included per month',
      'Preview short idea headlines and founder thesis quotes',
      'Full pitch deck & financial model attachments access',
      'Direct WhatsApp & calendar meeting coordination',
      'Extra chat quota pack available on demand (₹999 for 3 chats)',
      'Zero platform commission or broker fees on any deal',
    ],
    ctaLabel: 'Select Monthly Plan',
  },
  {
    id: 'yearly',
    name: 'Investor Annual Pass',
    badge: 'Best Value · Save 30%',
    priceMonthly: 3499,
    currency: '₹',
    discoveryCreditsPerMonth: 5,
    popular: true,
    description: 'Billed annually at ₹41,988/yr. Dedicated verification priority and uninterrupted founder deal flow.',
    features: [
      'Priority 4-hr expedited background verification check',
      '5 Direct bilateral chats renewed every month (60 chats/yr)',
      'Unrestricted short idea headlines and founder quote feeds',
      'Download vetted founder pitch decks and models (max 2 files/idea)',
      'Roll-over unused bilateral chat slots across billing months',
      'Direct mediator concierge assistance for confidential syncs',
      '100% neutral platform — 0% equity, 0% deal commission',
    ],
    ctaLabel: 'Select Annual Pass',
  },
  {
    id: 'fund',
    name: 'Institutional Syndicate',
    badge: 'Family Offices & Micro-VCs',
    priceMonthly: 14999,
    currency: '₹',
    discoveryCreditsPerMonth: 25,
    popular: false,
    description: 'For angel networks and institutional syndicates requiring multi-partner access.',
    features: [
      'Up to 5 verified partner accounts under single syndicate',
      '25 Direct bilateral founder chats per month',
      'Custom investment thesis alerts & early-stage deal alerts',
      'Dedicated compliance officer & custom bilateral NDA vaults',
      'Priority access to founders requesting assisted deck preparation',
      'Completely neutral mediator channel with end-to-end encryption',
    ],
    ctaLabel: 'Contact Syndicate Desk',
  },
];
